<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRepository extends EntityRepository
{
    function calcularTotalGastos(){
        $query = $this->getEntityManager()->createQuery('SELECT SUM (m.cantidad) FROM AppBundle:Movimiento m WHERE m.tipo=0');
            return $query->getResult();

    }
    function calcularTotalIngresos(){
        $query = $this->getEntityManager()->createQuery('SELECT SUM (m.cantidad)  FROM AppBundle:Movimiento m WHERE m.tipo=1');
            return $query->getResult();
    }
    function resumenGastoMes($mes,$tipo){
        $query = $this->getEntityManager()->createQuery("SELECT m.mes, SUM (m.cantidad) FROM AppBundle:Movimiento m WHERE m.tipo='.$tipo.' and m.mes='$mes'");
            return $query->getResult();
    }
    function cargarMovimiento($mes,$tipo){
        $qb = $this->getEntityManager()
            ->createQueryBuilder();
        $qb->select('m')
            ->from('AppBundle:Movimiento', 'm')
            ->where('m.mes LIKE :mes')
            ->setParameter('mes', '%'.$mes.'%');
        if($tipo){
            $qb->andWhere('m.tipo = :tipo')
                ->setParameter('tipo', $tipo);
        }
        ;
        return $qb;
    }
}
