# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    raul:
                        password: $2y$12$lN99h0SsCXvzvTWaWvKK4O1o85oyNYvKzB/5h99IUHexRoXSNTSbq
                        roles: 'ROLE_ADMIN'

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  login
                check_path:  login
            logout:
                path: logout
                target: /
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
